default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: /var/ka-lite/.kalite/database/content_khan_es.sqlite

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
